export default [
  { id: 1, name: "地點1", region: "高雄市", weight: 5 },
  { id: 2, name: "地點2", region: "台北市", weight: 9 },
  { id: 3, name: "地點3", region: "台中市", weight: 7 },
  { id: 4, name: "地點4", region: "新北市", weight: 8 },
  { id: 5, name: "地點5", region: "桃園市", weight: 6 },
  { id: 6, name: "地點6", region: "彰化縣", weight: 4 },
  { id: 7, name: "地點7", region: "南投縣", weight: 3 },
  { id: 8, name: "地點8", region: "嘉義市", weight: 2 },
  { id: 9, name: "地點9", region: "新竹市", weight: 5 },
  { id: 10, name: "地點10", region: "苗栗縣", weight: 4 },
  { id: 11, name: "地點11", region: "台東縣", weight: 3 },
  { id: 12, name: "地點12", region: "花蓮縣", weight: 4 },
  { id: 13, name: "地點13", region: "宜蘭縣", weight: 5 },
  { id: 14, name: "地點14", region: "屏東縣", weight: 6 },
  { id: 15, name: "地點15", region: "台南市", weight: 7 },
  { id: 16, name: "地點16", region: "金門縣", weight: 3 },
  { id: 17, name: "地點17", region: "澎湖縣", weight: 2 },
  { id: 18, name: "地點18", region: "基隆市", weight: 4 },
  { id: 19, name: "地點19", region: "新竹縣", weight: 5 },
  { id: 20, name: "地點20", region: "台中市", weight: 6 },
  // ... 更多地點
];
